'use strict';
const string = description => ({ type: 1, description });
const fields = names => Object.fromEntries(names.split(' ').filter(Boolean).map(name => [name, string(`${name}: pass as a string.`)]));
const spec = (description, required = '', optional = '', timeout_ms = 60000) => ({ description, required: fields(required), optional: fields(optional), permissions: [], datatype: '', timeout_ms });
function computerSpecs() {
  return {
    'computer.session': spec('Start/end/pause/status of approved computer use. scope=connected_browser controls ONLY the Chrome tab the user selected in Linux settings, preserving its existing sign-in without host input. scope=browser uses Muse Local Browser. scope=desktop uses approved host windows, blue control indicators and user takeover Pause. scope=isolated_desktop creates a headless private Cage desktop with independent input, clipboard and buses; apps use fresh profiles, no authenticated profile copying. No viewer/workspaces/portals or calibrated coordinate fallback in this separate desktop yet. It is input isolation, not filesystem confidentiality. Pause and Stop block new effects. Agent cannot resume; the user resumes locally. Tool results report capability gaps explicitly.', 'action', 'scope task session_id', 180000),
    'computer.observe': spec('Read current DOM in a selected browser tab or a persistent native AX tree. Prefer this to screenshots; full field readback verifies typing independently of previews. query is a JSON-encoded object {role?,name?,states?,exact:true|false,limit:1..256,scope:"visible"|"structural"}; name/role discovery avoids tabbing. Results contain stable ref_id and element_number, revision, URL/heading/text excerpt, coverage and omissions. Default compact output <=12 KiB; detail=full <=32 KiB. control_offset/control_limit paginate. view=image requests pixels with unchanged-frame suppression where supported. Covered host windows return unavailable capture metadata, not a navigation failure. Connected Chrome currently has DOM evidence but no integrated pixel capture. Separate desktop pixels exclude Muse indicators. A missing/stale AX tree is not evidence that a visible page failed to load.', '', 'query view force_image window_id surface layer_namespace monitor detail control_offset control_limit'),
    'computer.diagnose': spec('Refresh current selected-target state without input, focus, clipboard, navigation or permission prompts. A gated run permits at most three read-only probes total; each call has a five-second budget. Returns current compact DOM/AX/window observations, source freshness, contradictions, failed probes and next-route guidance. A stale or unavailable Chrome accessibility tree does not establish a failed page load; prefer the connected tab DOM/CDP when available. Diagnosis never approves recovery, replays input, clears an uncertain same-intent action or establishes task success. Pause still requires local user Resume.', '', 'window_id', 5000),
    'computer.control': spec('Use the best available operation: browser navigate url directly, type a complete string by direct DOM insertion, click/focus/reveal/set_checked/scroll an exact observed ref_id or element_number/unique element_label. Browser/native type supports edit_mode=replace|append|insert|replaceSelection; replace_all="true" means replace. It never submits. Browser operations preserve selected target identity and verify full text. expected_heading on navigate verifies the actual URL plus a visible heading; redirected destinations can differ and must be observed. Native semantic actions work on covered/off-workspace windows. Results include receipt with requested operation, attempts, chosen methods, latency, errors and verified effect. acknowledged input is not task success. Inspect failed calls; never replay possible/partial input. Host desktop also supports list_windows, desktop_context, list_apps, open_app, list_keybindings, list_workspaces, switch_workspace, move_window, close_window, activate, list_layers and observation-free compositor_key. Host coordinate format is a STRING containing JSON [x,y], normalized 0-1000 within the observed window or explicit layer; x/y fields are invalid. Layers require surface=layer, exact layer_namespace/monitor and a fresh observation_id. key/modifiers are case-insensitive; use actual configured bindings instead of assuming Alt+F4. Host physical/window operations currently have conservative legacy receipts with unverified effects; verify by reading state. Separate desktop supports list_apps/open_app/list_windows, semantic controls and graceful close; activation is acknowledged without an integrated success predicate. upload uses an exact file-input ref plus paths as a STRING containing a JSON array of absolute file paths in the locally approved folder; permission and file identity are rechecked before input. action=batch accepts actions as a STRING containing a JSON array; computer.batch is preferred. wait reads fresh state; view=image is optional. Prefer DOM/semantic actions over keyboard traversal. Pause requires user Resume. Stop cancels later actions.', '', 'action action_name app url expected_heading window_id observation_id ref_id element_number element_label coordinate start_coordinate end_coordinate button text edit_mode replace_all key modifiers scroll_direction scroll_amount workspace follow checked dialog_id decision paths actions query view force_image surface layer_namespace monitor duration detail control_offset control_limit'),
    'computer.batch': spec('Run 1-16 actions locally to reduce model round trips. actions is a STRING containing JSON [{"action":"type","element_label":"Paragraph","replace_all":"true","text":"Hello"},{"action":"click","element_label":"Save"}]. Each step resolves against current state and receives its own durable receipt. Unique labels are safer than changing ordinals. An error/Stop/Pause skips the remaining suffix. completed counts executed actions, not goal success. Final observation and per-step receipts explain what happened. Duplicate delivery returns stored results; never replay interrupted input.', 'actions', 'window_id observation_id view force_image detail control_offset control_limit', 180000),
    'computer.action': spec('Execute one typed operation with explicit deterministic expectations. request is a STRING containing JSON {operation,expect?:Predicate[],require?:Predicate[],requirementIds?:string[]}. Element operation ref/itemRefs may be observed ref_id strings; main expands and validates exact adapter refs. Operations include editText, click, invoke, focus, query, navigate, setChecked, select, scroll, reveal and dialog. Example {"operation":{"kind":"editText","ref":"observed-ref-id","edit":{"mode":"replace","text":"Hello","semantics":"plain_text","clipboard":"forbid","newlinePolicy":"literal_multiline"}}}. Main binds run/session/target/revision; caller JSON never grants permission. Effect is verified only by deterministic current evidence. Parent must report actions as attempted/unknown when receipts do not confirm them.', 'request', '', 180000),
    'computer.plan': spec('Execute a frozen muse.plan.v1 typed plan with act/assert/waitUntil/checkpoint steps under finite local budgets. request is a STRING containing the plan JSON. Main binds run/invoke/session. Every action must carry its observed target/revision and valid operation/expectations. Later stale refs are rejected rather than rebound by label. transition.bindAs is unsupported and rejects before all effects. Prefer computer.batch for short dynamic label-based sequences. Plan failure returns explicit skipped suffix and forbids replay.', 'request', '', 180000),
    'computer.run.start': spec('Start a grounded goal ledger. requirements is a STRING containing JSON Predicate[] with id,validator,validatorVersion:1,target,args. Supported validators include text.exact, element.checked/selected/focused, navigation.destination, dialog.state, window.closed/placement. Actions bind requirementIds explicitly. An empty ledger never implies task success. Local-only handoff: hosted parent reasoning is outside this companion.', 'requirements'),
    'computer.run.result': spec('Read compact structured execution trace and requirement statuses: verified_present/verified_absent/not_attempted/attempted_unverified/unknown. Contains important receipts, failures, latency and evidence metadata. Never claim tracking was entered if its requirement is not_attempted. Inspect deeper computer.trace.read details when needed. Model round-trip metrics are unavailable unless actually supplied; do not substitute action counts.', '', 'run_id'),
    'computer.trace.read': spec('Read bounded private execution telemetry. Pass run_id plus cursor for events. To inspect all detail after trace eviction, pass action_id, section=attempts|assertions|artifacts, offset and limit. max_bytes caps response. Raw typed text, passwords, URLs with private parameters and titles are excluded from durable telemetry.', '', 'run_id runId action_id actionId cursor section offset limit max_bytes'),
    'computer.evidence.read': spec('Read evidence metadata for a run. Missing/redacted/expired artifacts stay unavailable; do not imply screenshot contents from metadata. Detailed current content must be observed through the selected adapter.', 'evidence_id', 'run_id'),
    'screen.snap': spec('Explicitly request image evidence in the approved session. Fresh identical captures suppress pixels; force_image="true" recovers lost image context. Host covered windows return honest unavailable metadata; layers can be explicitly selected. Connected Chrome pixels are currently unsupported; use current DOM evidence. Native/Muse-own indicators are excluded, private Cage has no host overlay.', '', 'window_id surface layer_namespace monitor force_image detail control_offset control_limit'),
  };
}
module.exports = { computerSpecs };
